apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
namespace: polo
images:
- name: hello-gitops
  newName: snk0202/hello-gitops
  newTag: 86180419ba941837d3e96918c3ef29d7a2c52490
